### ISSUE TITLE
Existing bash script no longer works

### ISSUE THREAD

**Issue by nickthename** [toptal/haste-client#20]
Don't worry, I made it good again.

```
haste() { a=$(cat); curl -X POST -s -d "$a" http://hastebin.com/documents | awk -F '"' '{print "http://hastebin.com/"$4}'; }
```

Use:

```
cat file.txt | haste
```

It will use whatever you pipe to it. 

The one you have listed is using a messed up curl command.

**Comment by KeiroD** [comment]
... So it's 2017... and it appears that this command is no longer working for me. I've been trying variations of this command and have yet to get anything beyond the base url of my hastebin.

Can I get a little help on this?

**Comment by seejohnrun** [comment]
@KeiroD What error are you getting?

**Comment by KeiroD** [comment]
The haste is set up at the base subdomain, no subfolder setup.Similar to the following:

```
user@domain:~$ curl -X POST -d 'test' example.example.com /home/user/test.txt https://example.example.com | awk -F '"' '{print "https://example.example.com/"$4}'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    18  100    14  100     4    127     36 --:--:-- --:--:-- --:--:--   128
chttps://example.example.com/
url: (3) <url> malformed
100    18  100    14  100     4     33      9 --:--:-- --:--:-- --:--:--    40
```

And other variations, such as:

```
user@example:~$ curl --data-binary @/home/user/example.txt -X POST example.example.com
Cannot POST /
```

All of this is in an attempt to whittle it down to just `curl -F file=@/home/user/example.txt example.example.com`

My work-place has this sort of setup and I've been trying to duplicate that `curl -F` functionality and it's been... frustrating.

**Comment by KeiroD** [comment]
I almost had it... _almost_.

`#hastie() { a=$(file); curl -d "$a" -X POST http://paste.ituralde.com/documents | awk -F '"' '{print "http://paste.ituralde.com/"$4}'; }`

Works... sort of. It returns the following:

```
user@example:~$ hastie authorized.txt
Usage: file [-bcEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding] [--mime-type]
            [-e testname] [-F separator] [-f namefile] [-m magicfiles] file ...
       file -C [-m magicfiles]
       file [--help]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    20    0    20    0     0    180      0 --:--:-- --:--:-- --:--:--   181
http://subdomain.example.com/ocasoheheq
```

As you can see, it does return a link. Just an empty one. Heh. So this format works now.

`hastie() { a=$(cat); curl -d "$a" -X POST http://subdomain.example.com/documents | awk -F '"' '{print "http://subdomain.example.com/"$4}'; }`

However, going back to the original one results in the file that was `cat`'d simply... not returning a result. I suspect that the usage of `cat` here is the issue.

**Comment by seejohnrun** [comment]
What platform are you on @KeiroD ?

**Comment by KeiroD** [comment]
The server I was running the commands on was Ubuntu 16.04.3 LTS but I also have Arch.

Hmmmmm... as long as the example `haste` for bash is used ending in `/documents`, it works... but if I don't want to use `/documents`, I encounter loads of issues. I must've been idiotically using `cat` or something. I don't know, man.

As long as I stick with `/documents`, it works. I'd just rather not do that, though... but I understand if that's something that can't be easily done. (can it?)

**Comment by seejohnrun** [comment]
Nope - currently `/documents` is needed since that's the endpoint to which the paste gets uploaded.  Could change via a config but we're currently not set up to do so
