### ISSUE TITLE
cannot find my post

### ISSUE THREAD

**Issue by makiiii** [toptal/haste-client#36]
I followed the instructions from the readme.md. And this fails. I don't know why.

![image](https://user-images.githubusercontent.com/28750298/30536701-6d15ee42-9c99-11e7-8481-0a71ab36655d.png)

**Comment by seejohnrun** [comment]
Looks like your server maybe isn't supporting SSL correctly.  You'll get this error if you're trying to connect over `https:` but the handshake fails

**Comment by Numkil** [comment]
@seejohnrun 

This started happening to me too recently. Just connecting to https://hastebin.com so no custom settings.
This is on macos el capitan.

**Comment by heyitswither** [comment]
This is an issue with ruby on macos, please see https://github.com/google/google-api-ruby-client/issues/235
