### ISSUE TITLE
something went wrong!

### ISSUE THREAD

**Issue by SinixSpielt** [toptal/haste-client#44]
I dont now what i can do :x

**Comment by fabiocosta0305** [comment]
I can't save anything.

It asks a username and password (I can't say how to get it) and if you escape the browser dialog give this error message

**Comment by SinixSpielt** [comment]
Username and password? Who?
link: http://185.254.97.107/server/

**Comment by Sophiazoe** [comment]
> I can't save anything.
> 
> It asks a username and password (I can't say how to get it) and if you escape the browser dialog give this error message

Hey
