### ISSUE TITLE
hastebin.com can be accessed on plain HTTP

### ISSUE THREAD

**Issue by brunosaboia** [toptal/haste-client#48]
Hello,

I don't know if this is the proper place to share this, but here you go.

You can use http://hastebin.com, which will eavesdropping on the submission.

I think that hastebin.com should be HTTPS only.

Thanks.

**Comment by deniskaber** [comment]
Hello @brunosaboia! Thank you for the proposal.

I think this is no longer relevant as hastebin has been moved to https://www.toptal.com/developers/hastebin/ which no longer accepts non-secure http requests.
