### ISSUE TITLE
Chrome Extension 

### ISSUE THREAD

**Issue by Oscaramr** [toptal/haste-client#53]
I am not sure if there is a hastebin extension that supports custom urls if so can i get the link of it? If not i think you should implement it

**Comment by deniskaber** [comment]
Hi, @Oscaramr !
Thanks for such a nice idea!

I've checked Google Chrome Web Store and there is a hastebin extension there - https://chrome.google.com/webstore/detail/hastebin/jnjbjegfekjhdodgjblogcemdmdajocl
However it's not under our control.

You can try it out and check if it would do the job for you!

We don't have plans to create an extension ourselves in the near future. We are now focusing on improving the existing project.

**Comment by Oscaramr** [comment]
> Hi, @Oscaramr ! Thanks for such a nice idea!
> 
> I've checked Google Chrome Web Store and there is a hastebin extension there - https://chrome.google.com/webstore/detail/hastebin/jnjbjegfekjhdodgjblogcemdmdajocl However it's not under our control.
> 
> You can try it out and check if it would do the job for you!
> 
> We don't have plans to create an extension ourselves in the near future. We are now focusing on improving the existing project.

Go ahead for your project, you do what you want to do but i saw that extenstion and it doesnt allow for custom urls, which basically breaks the purpose of hosting your own haste bin. Maybe i can contact him and he could add it
