### ISSUE TITLE
Delete post

### ISSUE THREAD

**Issue by ffeelix** [toptal/haste-client#55]
Hello

How do i delete a post?

**Comment by konstrybakov** [comment]
Hello, @ffeelix! You currently cannot delete a bin via an API. But there are a few things you can do:
- wait, a bin's lifespan is 7 days. It will be removed after that
- if you have some sensitive information in your bin, please reach out to `support@toptal.com` with your request and it will be handled in a timely manner
- if the bin is in your self-hosted version, you can do this by directly removing the bin from the DB/Storage that you chose to use

Please, don't hesitate to reach for more info
